feat: replace the querystring package with the new URLSearchParams api
defunctzombie/node-url pull request #60
Opened 2021-12-20 21:39 UTC by bertyhell

During an npm install i got this message:
```
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
```

I tried to replace it in this new API, and all tests in node still succeed, **but I'm unsure if the supported browsers match with what this package supports.**

https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams

On MDN the support for URLSearchParams seems to be quite good:
![image](https://user-images.githubusercontent.com/1710840/146835910-58b31197-a729-470c-a62e-9087ed93a077.png)

https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams#browser_compatibility

This should reduce the package size by about 16%

2021-12-20 22:13 UTC, ljharb requested changes
They do not, I'm afraid.

`URL` and `URLSearchParams` can't be used here, because they don't exist in the majority of the browser range we support.

2021-12-20 22:13 UTC, ljharb commented on url.js
> +          this.query = Object.fromEntries(new URLSearchParams(this.search.substr(1)));
`Object.fromEntries` also won't work in our supported browsers, but at least this can come from https://npmjs.com/object.fromentries

2021-12-20 23:36 UTC, bertyhell commented
Ok, closing.
For future reference, where can I find the list of supported browsers for this package?

2021-12-20 23:36 UTC, closed without merging

2021-12-21 00:01 UTC, ljharb commented
At the moment, you can infer it by looking at what's tested - https://github.com/defunctzombie/node-url/actions/runs/1554926464 is node 0.8, so it's at least "any ES5 browser", but in practice this includes IE 6-8 as well.

2021-12-21 00:01 UTC, ljharb commented
At the moment, you can infer it by looking at what's tested - https://github.com/defunctzombie/node-url/actions/runs/1554926464 is node 0.8, so it's at least "any ES5 browser", but in practice this includes IE 6-8 as well.